import { execFileSync, spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import process from "node:process";

const repoRoot = process.cwd();
const vaultPath = resolveOpenVaultPath();
const smokeDirName = "OpenAgent Smoke";
const smokeDir = path.join(vaultPath, smokeDirName);
const controlDir = path.join(vaultPath, ".openagent");
const pluginDataPath = path.join(vaultPath, ".obsidian", "plugins", "openagent", "data.json");
const canvasPathRelative = `${smokeDirName}/smoke.canvas`;
const notePathRelative = `${smokeDirName}/context.md`;
const requestPath = path.join(controlDir, "smoke-request.json");
const resultPath = path.join(controlDir, "smoke-result.json");
const requestId = `smoke-${Date.now()}`;

syncPlugin();
writeFixtureFiles();
writeSmokeRequest();
restartObsidian();

const result = waitForResult(requestId, resultPath, 45_000);
if (result.status !== "ok") {
  console.error(JSON.stringify(result, null, 2));
  process.exit(1);
}

console.log(`Obsidian smoke test passed for ${result.taskId}`);
console.log(JSON.stringify(result, null, 2));

function syncPlugin() {
  execFileSync(process.execPath, [path.join(repoRoot, "scripts", "sync-obsidian-plugin.mjs")], {
    cwd: repoRoot,
    stdio: "inherit",
  });
}

function enableDevSmokeRequests() {
  fs.mkdirSync(path.dirname(pluginDataPath), { recursive: true });
  let existingState = {};
  if (fs.existsSync(pluginDataPath)) {
    try {
      existingState = JSON.parse(fs.readFileSync(pluginDataPath, "utf8"));
    } catch {
      existingState = {};
    }
  }

  fs.writeFileSync(pluginDataPath, `${JSON.stringify({
    ...existingState,
    settings: {
      ...(existingState.settings || {}),
      enableDevSmokeRequests: true,
    },
  }, null, 2)}\n`, "utf8");
}

function writeFixtureFiles() {
  fs.mkdirSync(smokeDir, { recursive: true });
  fs.mkdirSync(controlDir, { recursive: true });

  const noteContent = [
    "# OpenAgent Obsidian smoke context",
    "",
    "This note is generated by the smoke harness.",
    `Repository under test: ${repoRoot}`,
    "",
    "Expected behavior: the plugin should capture this file node and create a task successfully.",
    "",
  ].join("\n");

  const canvas = {
    nodes: [
      {
        id: "smoke-text",
        type: "text",
        x: 0,
        y: 0,
        width: 420,
        height: 180,
        text: "OpenAgent smoke test. Capture this canvas selection and create a task.",
      },
      {
        id: "smoke-file",
        type: "file",
        x: 480,
        y: 0,
        width: 420,
        height: 260,
        file: notePathRelative,
      },
    ],
    edges: [],
  };

  fs.writeFileSync(path.join(smokeDir, "context.md"), noteContent, "utf8");
  fs.writeFileSync(path.join(smokeDir, "smoke.canvas"), `${JSON.stringify(canvas, null, 2)}\n`, "utf8");
  if (fs.existsSync(resultPath)) {
    fs.unlinkSync(resultPath);
  }
}

function writeSmokeRequest() {
  const request = {
    id: requestId,
    canvasPath: canvasPathRelative,
    cwd: repoRoot,
    forceNewTask: true,
    runTask: true,
  };

  fs.writeFileSync(requestPath, `${JSON.stringify(request, null, 2)}\n`, "utf8");
}

function restartObsidian() {
  spawnSync("osascript", ["-e", 'tell application "Obsidian" to quit'], { stdio: "ignore" });
  waitForObsidianProcess(false, 15_000);
  enableDevSmokeRequests();
  execFileSync("open", ["-a", "Obsidian"], { stdio: "ignore" });
  waitForObsidianProcess(true, 20_000);
}

function waitForObsidianProcess(shouldExist, timeoutMs) {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    const running = spawnSync("pgrep", ["-x", "Obsidian"], { stdio: "ignore" }).status === 0;
    if (running === shouldExist) {
      return;
    }

    sleep(500);
  }

  throw new Error(shouldExist ? "Obsidian did not start in time." : "Obsidian did not quit in time.");
}

function waitForResult(expectedRequestId, filePath, timeoutMs) {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    if (fs.existsSync(filePath)) {
      const parsed = JSON.parse(fs.readFileSync(filePath, "utf8"));
      if (parsed?.requestId === expectedRequestId || (!parsed?.requestId && parsed?.status === "error")) {
        return parsed;
      }
    }

    sleep(1_000);
  }

  throw new Error(`Timed out waiting for ${filePath}`);
}

function resolveOpenVaultPath() {
  const configPath = path.join(os.homedir(), "Library", "Application Support", "obsidian", "obsidian.json");
  const parsed = JSON.parse(fs.readFileSync(configPath, "utf8"));
  const openVaultEntry = Object.values(parsed?.vaults || {}).find((vault) => vault?.open && vault?.path);
  if (!openVaultEntry?.path) {
    throw new Error("No open Obsidian vault was found in obsidian.json.");
  }

  return path.resolve(String(openVaultEntry.path));
}

function sleep(ms) {
  const shared = new SharedArrayBuffer(4);
  const view = new Int32Array(shared);
  Atomics.wait(view, 0, 0, ms);
}
